services:
  predictor-api:
    build:
      context: ./prediction-api
      dockerfile: Dockerfile
    container_name: heart-disease-predictor-api
    ports:
      - "5000:5000"
    networks:
      - heart-disease-network

  predictor-ui:
    build:
      context: ./prediction-ui
      dockerfile: Dockerfile
    container_name: heart-disease-predictor-ui
    environment:
      - PREDICTOR_API=http://predictor-api:5000/heart_disease_predictor
    ports:
      - "5001:5000" # Expose the UI on port 5001 externally but map to 5000 internally
    networks:
      - heart-disease-network

networks:
  heart-disease-network:
    driver: bridge
