name: Lint the code and run API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Steps for the Python linter
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linter on prediction-api
        run: |
          flake8 ./prediction-api

      - name: Run linter on prediction-ui
        run: |
          flake8 ./prediction-ui

      # Steps for the API testing
      - name: Install test dependencies
        run: |
          cd ./prediction-api
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest prediction-api/test_api.py
